### ISSUE TITLE
问下运行日志 内容是从哪里获取呢

### ISSUE THREAD

**Issue by zoubeihua** [ssssssss-team/magic-api#28]

**Comment by javamxd** [comment]
启动之后会识别日志框架，随后动态添加一个appender。在模拟测试请求期间有日志产生时，就发送给前端了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 晚上8:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] 问下运行日志 内容是从哪里获取呢 (#28)





 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zoubeihua** [comment]
> 启动之后会识别日志框架，随后动态添加一个appender。在模拟测试请求期间有日志时，就发送给前端了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ssssssss-team/magic-api" ***@***.***&gt;; 发送时间:&nbsp;2021年9月14日(星期二) 晚上8:06 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ssssssss-team/magic-api] 问下运行日志 内容是从哪里获取呢 (#28) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

我看前端日志渲染的时候没有请求接口 只有监听 ws_log 方法，这是后端emit的吗

**Comment by javamxd** [comment]
差不多啊，后端通过`websocket`给前台发送的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 晚上8:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ssssssss-team/magic-api] 问下运行日志 内容是从哪里获取呢 (#28)





  
启动之后会识别日志框架，随后动态添加一个appender。在模拟测试请求期间有日志时，就发送给前端了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ssssssss-team/magic-api" @.&gt;; 发送时间:&nbsp;2021年9月14日(星期二) 晚上8:06 @.&gt;; @.***&gt;; 主题:&nbsp;[ssssssss-team/magic-api] 问下运行日志 内容是从哪里获取呢 (#28) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
我看前端日志渲染的时候没有请求接口 只有监听 ws_log 方法，这是后端emit的吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zoubeihua** [comment]
> 差不多啊，后端通过`websocket`给前台发送的。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ssssssss-team/magic-api" ***@***.***&gt;; 发送时间:&nbsp;2021年9月14日(星期二) 晚上8:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ssssssss-team/magic-api] 问下运行日志 内容是从哪里获取呢 (#28) 启动之后会识别日志框架，随后动态添加一个appender。在模拟测试请求期间有日志时，就发送给前端了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ssssssss-team/magic-api" @.&gt;; 发送时间:&nbsp;2021年9月14日(星期二) 晚上8:06 @.&gt;; @.***&gt;; 主题:&nbsp;[ssssssss-team/magic-api] 问下运行日志 内容是从哪里获取呢 (#28) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 我看前端日志渲染的时候没有请求接口 只有监听 ws_log 方法，这是后端emit的吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

明白了 谢谢
