### ISSUE TITLE
页面上编辑了接口，但是数据库里和swagger没生效

### ISSUE THREAD

**Issue by just3019** [ssssssss-team/magic-api#29]
这个截图是页面上编辑结束的。response参数为reportCount，hitCount
![image](https://user-images.githubusercontent.com/5235712/133353862-06164db3-7fc5-4794-b0a1-4ffe6ce5ccb9.png)

这个截图是swagger展示的，hitNumber，reportNumber
![image](https://user-images.githubusercontent.com/5235712/133353950-a88f33b4-8a9e-4f86-b952-86840160df13.png)

这个是数据库的存储
```
{
  "properties" : { },
  "id" : "95ce1a51e6eb4974aaa3966be7f74aa4",
  "script" : null,
  "groupId" : "d47fce573fd54feeaed88f6971a4d402",
  "name" : "统计情报数和情报转事件数接口",
  "createTime" : null,
  "updateTime" : 1631668188476,
  "method" : "POST",
  "path" : "statisticCount",
  "parameters" : [ ],
  "option" : "[]",
  "requestBody" : "{\n    \"startTime\": \"开始时间\",\n    \"endTime\": \"截止时间\"\n}",
  "headers" : [ ],
  "paths" : [ ],
  "responseBody" : "{\n    \"code\": 1,\n    \"message\": \"success\",\n    \"data\": {\n        \"reportNumber\": \"情报上报数量\",\n        \"hitNumber\": \"情报命中数量\"\n    },\n    \"timestamp\": 1631612822033,\n    \"executeTime\": 2\n}",
  "description" : "统计情报上报数量、情报命中数量",
  "requestBodyDefinition" : {
    "name" : "",
    "value" : "",
    "description" : "",
    "required" : false,
    "dataType" : "Object",
    "type" : null,
    "defaultValue" : null,
    "validateType" : "",
    "error" : "",
    "expression" : "",
    "children" : [ {
      "name" : "startTime",
      "value" : "开始时间",
      "description" : "",
      "required" : false,
      "dataType" : "String",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ ]
    }, {
      "name" : "endTime",
      "value" : "截止时间",
      "description" : "",
      "required" : false,
      "dataType" : "String",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ ]
    } ]
  },
  "responseBodyDefinition" : {
    "name" : "",
    "value" : "",
    "description" : "",
    "required" : false,
    "dataType" : "Object",
    "type" : null,
    "defaultValue" : null,
    "validateType" : "",
    "error" : "",
    "expression" : "",
    "children" : [ {
      "name" : "code",
      "value" : "1",
      "description" : "",
      "required" : false,
      "dataType" : "Integer",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ ]
    }, {
      "name" : "message",
      "value" : "success",
      "description" : "",
      "required" : false,
      "dataType" : "String",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ ]
    }, {
      "name" : "data",
      "value" : "",
      "description" : "",
      "required" : false,
      "dataType" : "Object",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ {
        "name" : "reportNumber",
        "value" : "情报上报数量",
        "description" : "情报上报数量",
        "required" : false,
        "dataType" : "String",
        "type" : null,
        "defaultValue" : null,
        "validateType" : "",
        "error" : "",
        "expression" : "",
        "children" : [ ]
      }, {
        "name" : "hitNumber",
        "value" : "情报命中数量",
        "description" : "情报命中数量",
        "required" : false,
        "dataType" : "String",
        "type" : null,
        "defaultValue" : null,
        "validateType" : "",
        "error" : "",
        "expression" : "",
        "children" : [ ]
      } ]
    }, {
      "name" : "timestamp",
      "value" : "1631612822033",
      "description" : "",
      "required" : false,
      "dataType" : "Long",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ ]
    }, {
      "name" : "executeTime",
      "value" : "2",
      "description" : "",
      "required" : false,
      "dataType" : "Integer",
      "type" : null,
      "defaultValue" : null,
      "validateType" : "",
      "error" : "",
      "expression" : "",
      "children" : [ ]
    } ]
  },
  "optionMap" : { }
}
================================
var res={
    "reportCount":"情报上报数量",
    "hitCount":"情报命中数量"
}
return res;
```

希望页面上编辑完接口后，swagger和数据库可以实时生效。

**Comment by javamxd** [comment]
执行完毕之后，在保存一次就可以了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 上午9:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] 页面上编辑了接口，但是数据库里和swagger没生效 (#29)





 
这个截图是页面上编辑结束的。response参数为reportCount，hitCount
 
 
这个截图是swagger展示的，hitNumber，reportNumber
 
 
这个是数据库的存储
 {   "properties" : { },   "id" : "95ce1a51e6eb4974aaa3966be7f74aa4",   "script" : null,   "groupId" : "d47fce573fd54feeaed88f6971a4d402",   "name" : "统计情报数和情报转事件数接口",   "createTime" : null,   "updateTime" : 1631668188476,   "method" : "POST",   "path" : "statisticCount",   "parameters" : [ ],   "option" : "[]",   "requestBody" : "{\n    \"startTime\": \"开始时间\",\n    \"endTime\": \"截止时间\"\n}",   "headers" : [ ],   "paths" : [ ],   "responseBody" : "{\n    \"code\": 1,\n    \"message\": \"success\",\n    \"data\": {\n        \"reportNumber\": \"情报上报数量\",\n        \"hitNumber\": \"情报命中数量\"\n    },\n    \"timestamp\": 1631612822033,\n    \"executeTime\": 2\n}",   "description" : "统计情报上报数量、情报命中数量",   "requestBodyDefinition" : {     "name" : "",     "value" : "",     "description" : "",     "required" : false,     "dataType" : "Object",     "type" : null,     "defaultValue" : null,     "validateType" : "",     "error" : "",     "expression" : "",     "children" : [ {       "name" : "startTime",       "value" : "开始时间",       "description" : "",       "required" : false,       "dataType" : "String",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ ]     }, {       "name" : "endTime",       "value" : "截止时间",       "description" : "",       "required" : false,       "dataType" : "String",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ ]     } ]   },   "responseBodyDefinition" : {     "name" : "",     "value" : "",     "description" : "",     "required" : false,     "dataType" : "Object",     "type" : null,     "defaultValue" : null,     "validateType" : "",     "error" : "",     "expression" : "",     "children" : [ {       "name" : "code",       "value" : "1",       "description" : "",       "required" : false,       "dataType" : "Integer",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ ]     }, {       "name" : "message",       "value" : "success",       "description" : "",       "required" : false,       "dataType" : "String",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ ]     }, {       "name" : "data",       "value" : "",       "description" : "",       "required" : false,       "dataType" : "Object",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ {         "name" : "reportNumber",         "value" : "情报上报数量",         "description" : "情报上报数量",         "required" : false,         "dataType" : "String",         "type" : null,         "defaultValue" : null,         "validateType" : "",         "error" : "",         "expression" : "",         "children" : [ ]       }, {         "name" : "hitNumber",         "value" : "情报命中数量",         "description" : "情报命中数量",         "required" : false,         "dataType" : "String",         "type" : null,         "defaultValue" : null,         "validateType" : "",         "error" : "",         "expression" : "",         "children" : [ ]       } ]     }, {       "name" : "timestamp",       "value" : "1631612822033",       "description" : "",       "required" : false,       "dataType" : "Long",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ ]     }, {       "name" : "executeTime",       "value" : "2",       "description" : "",       "required" : false,       "dataType" : "Integer",       "type" : null,       "defaultValue" : null,       "validateType" : "",       "error" : "",       "expression" : "",       "children" : [ ]     } ]   },   "optionMap" : { } } ================================ var res={     "reportCount":"情报上报数量",     "hitCount":"情报命中数量" } return res;  
希望页面上编辑完接口后，swagger和数据库可以实时生效。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by just3019** [comment]
感谢！！！之前直接点保存不生效。

**Comment by jonahzheng** [comment]
swagger页面无法访问，是什么原因
